from __future__ import annotations

from typing import Protocol

from app.core.entities import Book, BorrowTransaction, Tag, User


class UserRepository(Protocol):
    def get_by_email(self, email: str) -> User | None: ...

    def get_by_id(self, user_id: int) -> User | None: ...

    def add(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...


class TagRepository(Protocol):
    def list(self) -> list[Tag]: ...

    def get_by_id(self, tag_id: int) -> Tag | None: ...

    def get_by_name(self, name: str) -> Tag | None: ...

    def get_by_names(self, names: list[str]) -> list[Tag]: ...

    def add(self, tag: Tag) -> Tag: ...

    def update(self, tag: Tag) -> Tag: ...

    def delete(self, tag_id: int) -> None: ...


class BookRepository(Protocol):
    def add(self, book: Book) -> Book: ...

    def list(self, q: str | None, available_only: bool) -> list[Book]: ...

    def get_by_id(self, book_id: int) -> Book | None: ...

    def update(self, book: Book) -> Book: ...

    def delete(self, book_id: int) -> None: ...


class BorrowingRepository(Protocol):
    def add(self, borrowing: BorrowTransaction) -> BorrowTransaction: ...

    def get_by_id(self, borrowing_id: int) -> BorrowTransaction | None: ...

    def list_by_user(self, user_id: int) -> list[BorrowTransaction]: ...

    def list_return_requests(self) -> list[BorrowTransaction]: ...

    def update(self, borrowing: BorrowTransaction) -> BorrowTransaction: ...
